import NavBar from '../components/NavBar/NavBar'
import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>BoorIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/IconBoxIT.svg" />
      </Head>
    <NavBar/>
    <Component {...pageProps} />
    </>
  )
  
}

export default MyApp
